// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOYcA2gbnmvU4gFfQuS6wxyzofrL3NTXA',
    appId: '1:852749702030:web:5472bfffcd2060dbf04adf',
    messagingSenderId: '852749702030',
    projectId: 'my-personal-journal-2161b',
    authDomain: 'my-personal-journal-2161b.firebaseapp.com',
    storageBucket: 'my-personal-journal-2161b.firebasestorage.app',
    measurementId: 'G-6P08PW56GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANwpIG4wEuyAJ54UuoKSwpMafR3YEf2bE',
    appId: '1:852749702030:android:f1632841652982b7f04adf',
    messagingSenderId: '852749702030',
    projectId: 'my-personal-journal-2161b',
    storageBucket: 'my-personal-journal-2161b.firebasestorage.app',
  );
}
